"""The part-orientation facts the TEST CORPUS's own drawings carry.

WHY THIS EXISTS
---------------
``assembly_orientation`` refuses to emit a position file for a part that is
bought as a catalogue part and whose (footprint, house, catalogue number) pair
nobody has measured. That is the point of it.

Most boards in this corpus are drawn on SYNTHETIC seed land patterns that exist
only in this repository — ``R_0805`` and ``C_0805`` are generated by the
worker's own seed synthesizer and are deliberately NOT the official KiCad parts
of the same name (see their ``provenance_note`` in ``footprints.lock.json``),
and ``Diode_SMD:D_SMA`` was hand-authored in-repo. No vendor draws any of them,
so no pair involving one has a reference to measure against, and no row about
one will ever appear in the shipped ledger.

Suites that emit assembly outputs from those boards are measuring BOM grouping,
frame arithmetic, gates, service checks and package assembly — not orientation,
which has its own suite. :func:`install` gives them a ledger that is the SHIPPED
one plus a declared "there is nothing to measure here" for each of those
drawings, so the corpus states that fact ONCE instead of each suite working
around the gate its own way.

WHAT THIS DELIBERATELY IS NOT. It does not weaken the gate for any real part:
every added row is a DECLARED no-reference, which ``OrientationRecord``
validates can carry no numbers at all, and it names each fixture drawing
explicitly. A board that buys a REAL footprint under an unmeasured catalogue
number still refuses, in every suite, exactly as it does in production.
"""

from __future__ import annotations

from pcb_worker import assembly_orientation as aor
from pcb_worker import orientation_ledger as ol
from pcb_worker import part_orientation as po

#: Drawings this corpus places that no vendor has a counterpart for. Each must
#: be ABSENT from the shipped ledger's declarations — a duplicate key is a
#: refusal, which is the check that keeps this list from quietly shadowing a
#: real row.
FIXTURE_DRAWINGS = (
    "C_0805",
    "Diode_SMD:D_SMA",
    "R_0805",
)

REASON = ("a test-corpus drawing: synthesized or hand-authored in-repo, with no "
          "vendor package drawing anywhere to measure it against")


def corpus_ledger() -> ol.OrientationLedger:
    """The shipped ledger plus this corpus's own declarations."""
    shipped = ol.load_ledger()
    declared = shipped.declared + tuple(
        ol.OrientationRecord(footprint=ref, house=None, part=None,
                             verdict=po.VERDICT_NO_REFERENCE, declared=True,
                             reason=REASON)
        for ref in FIXTURE_DRAWINGS)
    return ol.OrientationLedger(declared=declared, measured=shipped.measured)


def install(monkeypatch) -> ol.OrientationLedger:
    """Make :func:`corpus_ledger` the ledger every emitter in this test reads.

    Substitutes the module-level CACHE, not the lookup logic: the emitters
    still do the real join and the real three-state fold — they are simply
    reading a ledger that knows about the drawings this corpus is built on.
    """
    ledger = corpus_ledger()
    monkeypatch.setattr(aor, "_DEFAULT", ledger)
    return ledger
