"""Canonical component-placement geometry for the PCB worker.

Single source of truth for the KiCad footprint-placement transform: rotate a
component-LOCAL offset by the placement angle, and translate it to the
component's board position. gerber.py, drc.py and route_bridge.py all delegate
here so there is exactly ONE rotation implementation in pcb_worker (DRY), and
no path can silently drift to a different sign.

Rotation convention (pinned by tests/test_rotation.py against a real
KiCad-authored fixture):

    KiCad applies a footprint ``(at x y rot)`` angle CLOCKWISE in the file's
    coordinate frame (Y grows downward) — i.e. negate the angle before applying
    the standard CCW rotation matrix (``math.radians(-deg)``). This is the exact
    convention the agent_router KiCad reader encodes
    (``kicad_io._transform_position`` uses ``radians(-rotation)``), which is the
    ground truth. The previous ``+deg`` (CCW) form flashed pads MIRRORED about
    the component centre versus KiCad, so a connector authored at rotation 90
    landed off its routed trace endpoints (docket 019f3ba0f455).

    0 deg is rotation-invariant and short-circuits (returns the inputs
    unchanged, exactly — no float drift), so the rotation_deg=0 gerber goldens
    are unaffected by the sign fix.

    (Boards authored in the pcb-architect dialect use the OPPOSITE sign for their
    ``rotation`` field; reconciling that is an IMPORT-layer concern — negate at
    import — not this worker's, whose rotation_deg is defined as KiCad-equivalent.)

Equivalence note (why consolidating three call sites is safe): route_bridge's
former hand-written ``radians(+deg)`` matrix ``(px·cos d + py·sin d,
−px·sin d + py·cos d)`` is algebraically IDENTICAL to the ``radians(-deg)`` form
here — expand ``cos(-d)=cos d`` and ``sin(-d)=−sin d`` and both collapse to the
same closed form. tests/test_geometry.py proves this across many angles.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Any

# The single authority for the placement-convention version.  Any change to the
# rotation sign or bottom-side mirror below MUST bump this so a downstream
# consumer (e.g. the K2 compiler's board provenance) records a detectable
# identity change rather than silently re-placing geometry under the old label.
TRANSFORM_VERSION = "kicad-flip-v1"

from .resolved_board import (
    ArcGeometry,
    CircleGeometry,
    GraphicGeometry,
    Layer,
    LineGeometry,
    PolygonGeometry,
    Side,
)


def is_top(layer: Any) -> bool:
    """A component/trace is on the top side unless it explicitly says bottom."""
    if isinstance(layer, str):
        return layer.strip().lower() not in ("bottom", "b.cu", "back")
    return True


def rotate_local_offset(px: float, py: float, deg: float) -> tuple[float, float]:
    """Rotate a component-LOCAL pad offset by *deg* using KiCad's footprint-angle
    convention, so the resulting flash lands on KiCad's own absolute pad position.

    See the module docstring for the full clockwise-convention rationale (KiCad
    negates the angle; pinned by tests/test_rotation.py; docket 019f3ba0f455).

    0 deg is rotation-invariant and short-circuits, returning the inputs
    unchanged (exact, no float drift).
    """
    if deg == 0.0:
        return px, py
    r = math.radians(-deg)
    c, s = math.cos(r), math.sin(r)
    return px * c - py * s, px * s + py * c


def place_point(cx: float, cy: float, deg: float,
                lx: float, ly: float) -> tuple[float, float]:
    """Rotate a component-LOCAL point (lx, ly) by *deg* (via ``rotate_local_offset``)
    and translate by the component's board placement (cx, cy) — the exact pad
    convention KiCad's reader (kicad_io._transform_position) applies."""
    ox, oy = rotate_local_offset(lx, ly, deg)
    return cx + ox, cy + oy


@dataclass(frozen=True)
class PlacementTransform:
    """Place footprint-local geometry on either board side.

    KiCad's bottom-side footprint operation mirrors the local Y axis before
    applying the footprint rotation.  The same reflection swaps explicit
    front/back technical layers and negates local feature orientation.  Layer
    wildcards (for example ``*.Cu`` and ``*.Mask``) deliberately survive.

    The convention is pinned by ``k1_bottom_oracle.kicad_pcb``, generated by
    pcbnew 9.0.9 from an asymmetric top-side footprint and evaluated after a
    native ``FOOTPRINT.Flip`` operation.
    """

    position: tuple[float, float]
    rotation_deg: float
    side: Side

    def __post_init__(self) -> None:
        if (not isinstance(self.position, tuple) or len(self.position) != 2
                or any(isinstance(v, bool) or not isinstance(v, (int, float))
                       or not math.isfinite(v) for v in self.position)):
            raise ValueError("PlacementTransform.position must be a finite tuple")
        if (isinstance(self.rotation_deg, bool)
                or not isinstance(self.rotation_deg, (int, float))
                or not math.isfinite(self.rotation_deg)):
            raise ValueError("PlacementTransform.rotation_deg must be finite")
        if not isinstance(self.side, Side):
            raise TypeError("PlacementTransform.side must be a Side")

    def point(self, local: tuple[float, float]) -> tuple[float, float]:
        """Transform one immutable footprint-local point to board coordinates."""
        if (not isinstance(local, tuple) or len(local) != 2
                or any(isinstance(v, bool) or not isinstance(v, (int, float))
                       or not math.isfinite(v) for v in local)):
            raise ValueError("local point must be a finite tuple")
        lx, ly = local
        if self.side is Side.BOTTOM:
            ly = -ly
        return place_point(
            self.position[0], self.position[1], self.rotation_deg, lx, ly,
        )

    def angle(self, local_degrees: float) -> float:
        """Transform a local feature orientation to KiCad board orientation."""
        if (isinstance(local_degrees, bool)
                or not isinstance(local_degrees, (int, float))
                or not math.isfinite(local_degrees)):
            raise ValueError("local angle must be finite")
        combined = (self.rotation_deg + local_degrees
                    if self.side is Side.TOP
                    else self.rotation_deg - local_degrees)
        return combined % 360.0

    def layer(self, local: Layer) -> Layer:
        return local if self.side is Side.TOP else local.flipped()

    def layers(self, local: tuple[Layer, ...]) -> tuple[Layer, ...]:
        return tuple(self.layer(layer) for layer in local)

    def graphic(self, local: GraphicGeometry) -> GraphicGeometry:
        """Transform every supported graphic primitive without special cases."""
        if isinstance(local, LineGeometry):
            return LineGeometry(self.point(local.a), self.point(local.b))
        if isinstance(local, CircleGeometry):
            return CircleGeometry(self.point(local.center), local.radius_mm)
        if isinstance(local, ArcGeometry):
            return ArcGeometry(
                self.point(local.start), self.point(local.mid), self.point(local.end),
            )
        if isinstance(local, PolygonGeometry):
            return PolygonGeometry(tuple(self.point(point) for point in local.points))
        raise TypeError(f"unsupported graphic geometry {type(local)!r}")
