package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"testing"
	"time"
)

// controlCapBytes is the host's bound on one panel IPC message in either
// direction (PluginPayloadLimits.CONTROL_BYTES). Anything larger is replaced by
// a payload_too_large error before the panel ever sees it.
const controlCapBytes = 64 * 1024

// fileHost answers host.pdf.generate with a canned PDF and host.dialogs.* with
// a canned pick.
type fileHost struct {
	pdf       []byte
	pageCount int
	picker    json.RawMessage
	calls     []string
}

func (h *fileHost) callCapability(capability string, _ map[string]interface{}) (json.RawMessage, *rpcError) {
	h.calls = append(h.calls, capability)
	switch capability {
	case "host.pdf.generate":
		return json.RawMessage(fmt.Sprintf(
			`{"success":true,"result":{"bytes_b64":%q,"byte_size":%d,"page_count":%d,"content_type":"application/pdf"}}`,
			base64.StdEncoding.EncodeToString(h.pdf), len(h.pdf), h.pageCount)), nil
	case "host.dialogs.file_picker":
		return h.picker, nil
	}
	return nil, &rpcError{Code: -32601, Message: "unexpected capability " + capability}
}

func replyBytes(t *testing.T, result map[string]interface{}) int {
	t.Helper()
	b, err := json.Marshal(result)
	if err != nil {
		t.Fatalf("marshal tool result: %v", err)
	}
	return len(b)
}

// oversizePDF is a synthetic PDF body well over the cap, with position-dependent
// content so a mis-ordered or duplicated chunk cannot reassemble by luck.
func oversizePDF() []byte {
	pdf := make([]byte, 200_000)
	copy(pdf, []byte("%PDF-1.7\n"))
	for i := 9; i < len(pdf); i++ {
		pdf[i] = byte(i*7 + i/251)
	}
	return pdf
}

// freshStore empties the transfer store and restores the real clock, so one
// test's leftovers cannot answer another's token.
func freshStore(t *testing.T) {
	t.Helper()
	transfers = map[string]*pdfTransfer{}
	now = time.Now
	t.Cleanup(func() {
		transfers = map[string]*pdfTransfer{}
		now = time.Now
	})
}

// chunks pulls a whole transfer the way the panel does — slices from offset 0
// until eof — asserting every reply fits the cap.
func chunks(t *testing.T, host capabilityCaller, token string, total int) []byte {
	t.Helper()
	var got []byte
	for round := 0; ; round++ {
		if round > 64 {
			t.Fatalf("chunk loop did not reach eof after %d rounds (%d bytes)", round, len(got))
		}
		chunk := toolNametagReadChunk(host, mustArgs(t, map[string]interface{}{
			"token": token, "offset": len(got),
		}))
		if ok, _ := chunk["success"].(bool); !ok {
			t.Fatalf("read chunk at %d failed: %+v", len(got), chunk)
		}
		if size := replyBytes(t, chunk); size > controlCapBytes {
			t.Fatalf("chunk reply is %d bytes, over the %d-byte cap", size, controlCapBytes)
		}
		if chunk["total_bytes"] != total {
			t.Fatalf("total_bytes %v does not match the %d generated bytes", chunk["total_bytes"], total)
		}
		data, err := base64.StdEncoding.DecodeString(chunk["bytes_b64"].(string))
		if err != nil {
			t.Fatalf("chunk base64: %v", err)
		}
		if len(data) != chunk["length"] {
			t.Fatalf("chunk reports length %v but carries %d bytes", chunk["length"], len(data))
		}
		got = append(got, data...)
		if eof, _ := chunk["eof"].(bool); eof {
			return got
		}
		if len(data) == 0 {
			t.Fatalf("chunk carried no bytes and did not report eof at offset %d", len(got))
		}
	}
}

// TestPanelPDFTransferStaysUnderTheControlCap is the panel round-trip oracle: a
// PDF far larger than one IPC message reaches the panel intact, as a token plus
// slices that each fit the cap; the transfer is released once the caller has
// it; and the inline-bytes result it replaces would not have fit.
func TestPanelPDFTransferStaysUnderTheControlCap(t *testing.T) {
	freshStore(t)
	pdf := oversizePDF()
	host := &fileHost{pdf: pdf, pageCount: 3}

	args := mustArgs(t, map[string]interface{}{
		"icon_png_base64":  "Zm9v",
		"deliver_by_token": true,
		"rows":             []map[string]interface{}{{"name": "Ada"}, {"name": "Grace Hopper"}},
	})

	res := toolNametagGenerate(host, args)
	if ok, _ := res["success"].(bool); !ok {
		t.Fatalf("generate failed: %+v", res)
	}
	if _, inline := res["bytes_b64"]; inline {
		t.Fatalf("deliver_by_token must not carry the bytes inline: %v", keys(res))
	}
	if size := replyBytes(t, res); size > controlCapBytes {
		t.Fatalf("generate reply is %d bytes, over the %d-byte cap", size, controlCapBytes)
	}

	token, _ := res["token"].(string)
	if token == "" {
		t.Fatalf("generate returned no token: %+v", res)
	}
	if res["byte_size"] != len(pdf) {
		t.Fatalf("byte_size %v does not match the %d generated bytes", res["byte_size"], len(pdf))
	}
	if len(pdf) <= controlCapBytes {
		t.Fatalf("fixture is not over the cap: %d bytes", len(pdf))
	}
	if res["page_count"] != 3 {
		t.Fatalf("page_count: want 3, got %v", res["page_count"])
	}

	if got := chunks(t, host, token, len(pdf)); !bytes.Equal(got, pdf) {
		t.Fatalf("reassembled %d bytes, want the %d generated bytes", len(got), len(pdf))
	}

	// A finished transfer is released: the token stops answering, and nothing
	// holds the bytes.
	after := toolNametagReadChunk(host, mustArgs(t, map[string]interface{}{"token": token}))
	if after["error_code"] != "transfer_not_found" {
		t.Fatalf("a completed transfer must be refused by name: %+v", after)
	}
	if len(transfers) != 0 {
		t.Fatalf("store still holds %d transfers after the eof slice", len(transfers))
	}

	// The falsifier: the inline-bytes result this replaces is far over the cap,
	// so the host would swap it for payload_too_large and the panel would show
	// no preview at all.
	inline := toolNametagGenerate(host, mustArgs(t, map[string]interface{}{
		"icon_png_base64": "Zm9v",
		"rows":            []map[string]interface{}{{"name": "Ada"}, {"name": "Grace Hopper"}},
	}))
	if size := replyBytes(t, inline); size <= controlCapBytes {
		t.Fatalf("inline reply is only %d bytes — the fixture no longer proves the cap is exceeded", size)
	}
}

// TestConcurrentTransfersAllComplete — panels do not see each other, so several
// transfers in flight at once must each deliver their own bytes whole.
func TestConcurrentTransfersAllComplete(t *testing.T) {
	freshStore(t)
	const panels = 8
	args := mustArgs(t, map[string]interface{}{
		"icon_png_base64":  "Zm9v",
		"deliver_by_token": true,
		"rows":             []map[string]interface{}{{"name": "Ada"}},
	})

	tokens := make([]string, panels)
	pdfs := make([][]byte, panels)
	hosts := make([]*fileHost, panels)
	for i := range tokens {
		// Each panel's PDF differs, so a transfer serving another's bytes fails.
		pdf := oversizePDF()
		pdf[100] = byte(i)
		pdfs[i] = pdf
		hosts[i] = &fileHost{pdf: pdf, pageCount: 1}
		res := toolNametagGenerate(hosts[i], args)
		tokens[i], _ = res["token"].(string)
		if tokens[i] == "" {
			t.Fatalf("panel %d got no token: %+v", i, res)
		}
	}
	// Interleave the first slice of every transfer before finishing any.
	for i, token := range tokens {
		first := toolNametagReadChunk(hosts[i], mustArgs(t, map[string]interface{}{"token": token, "offset": 0}))
		if ok, _ := first["success"].(bool); !ok {
			t.Fatalf("panel %d's first slice failed: %+v", i, first)
		}
	}
	for i, token := range tokens {
		if got := chunks(t, hosts[i], token, len(pdfs[i])); !bytes.Equal(got, pdfs[i]) {
			t.Fatalf("panel %d reassembled the wrong bytes", i)
		}
	}
}

// TestTransferRefusals — every way a token can fail to name live bytes is one
// structured error the panel can act on, and an expired transfer is one of them
// rather than a silent empty slice.
func TestTransferRefusals(t *testing.T) {
	freshStore(t)
	host := &fileHost{pdf: []byte("%PDF-1.7\n"), pageCount: 1}
	args := mustArgs(t, map[string]interface{}{
		"icon_png_base64":  "Zm9v",
		"deliver_by_token": true,
		"rows":             []map[string]interface{}{{"name": "Ada"}},
	})

	for name, bad := range map[string]map[string]interface{}{
		"no token":      {"offset": 0},
		"blank token":   {"token": "   "},
		"unknown token": {"token": "0123456789abcdef0123456789abcdef"},
	} {
		res := toolNametagReadChunk(host, mustArgs(t, bad))
		if ok, _ := res["success"].(bool); ok {
			t.Fatalf("%s: expected a failure, got %+v", name, res)
		}
		if code, _ := res["error_code"].(string); code == "" {
			t.Fatalf("%s: failure carries no error_code: %+v", name, res)
		}
	}

	live, _ := toolNametagGenerate(host, args)["token"].(string)
	past := toolNametagReadChunk(host, mustArgs(t, map[string]interface{}{"token": live, "offset": 1000}))
	if code, _ := past["error_code"].(string); code != "schema_validation_failed" {
		t.Fatalf("an offset past the end must be refused: %+v", past)
	}

	// Nothing has read it for longer than staleTransfer: the token stops
	// answering rather than serving bytes no panel is waiting for.
	base := time.Now()
	now = func() time.Time { return base.Add(staleTransfer + time.Second) }
	expired := toolNametagReadChunk(host, mustArgs(t, map[string]interface{}{"token": live}))
	if expired["error_code"] != "transfer_not_found" {
		t.Fatalf("an expired transfer must be refused by name: %+v", expired)
	}
	if len(transfers) != 0 {
		t.Fatalf("an expired transfer must be dropped, store holds %d", len(transfers))
	}
}

// TestTransferStoreIsBounded — the store holds at most transferSlots entries;
// delivering past the bound drops the least recently read one instead of
// growing without limit.
func TestTransferStoreIsBounded(t *testing.T) {
	freshStore(t)
	host := &fileHost{pdf: []byte("%PDF-1.7\n"), pageCount: 1}
	args := mustArgs(t, map[string]interface{}{
		"icon_png_base64":  "Zm9v",
		"deliver_by_token": true,
		"rows":             []map[string]interface{}{{"name": "Ada"}},
	})

	// A monotonic clock so "least recently read" is unambiguous.
	base := time.Now()
	tick := 0
	now = func() time.Time { tick++; return base.Add(time.Duration(tick) * time.Millisecond) }

	first, _ := toolNametagGenerate(host, args)["token"].(string)
	for i := 0; i < transferSlots; i++ {
		if token, _ := toolNametagGenerate(host, args)["token"].(string); token == "" {
			t.Fatalf("delivery %d got no token", i)
		}
	}
	if len(transfers) > transferSlots {
		t.Fatalf("store grew to %d entries, past the %d-slot bound", len(transfers), transferSlots)
	}
	res := toolNametagReadChunk(host, mustArgs(t, map[string]interface{}{"token": first}))
	if res["error_code"] != "transfer_not_found" {
		t.Fatalf("the oldest transfer must be evicted by name: %+v", res)
	}
}

// TestPickIconReturnsPathOrCancel — the panel's route to a large icon: a path
// crosses the bridge, never the PNG.
func TestPickIconReturnsPathOrCancel(t *testing.T) {
	host := &fileHost{picker: json.RawMessage(`{"success":true,"result":{"cancelled":false,"path":"/home/me/logo.png"}}`)}
	res := toolNametagPickIcon(host, nil)
	if ok, _ := res["success"].(bool); !ok || res["path"] != "/home/me/logo.png" {
		t.Fatalf("pick icon: %+v", res)
	}
	if cancelled, _ := res["cancelled"].(bool); cancelled {
		t.Fatalf("pick icon reported cancelled on a pick: %+v", res)
	}
	if len(host.calls) != 1 || host.calls[0] != "host.dialogs.file_picker" {
		t.Fatalf("expected one file_picker call, got %v", host.calls)
	}

	host = &fileHost{picker: json.RawMessage(`{"success":true,"result":{"cancelled":true}}`)}
	res = toolNametagPickIcon(host, nil)
	if cancelled, _ := res["cancelled"].(bool); !cancelled {
		t.Fatalf("cancel must be reported as cancelled, not a failure: %+v", res)
	}

	host = &fileHost{picker: json.RawMessage(`{"success":false,"error_code":"dialog_unavailable","error_message":"no UI"}`)}
	res = toolNametagPickIcon(host, nil)
	if ok, _ := res["success"].(bool); ok {
		t.Fatalf("a picker failure must surface as a failure: %+v", res)
	}
	if res["error_code"] != "dialog_unavailable" {
		t.Fatalf("error_code not surfaced: %+v", res)
	}
}
