#!/usr/bin/env python3
"""Regenerate the part-orientation ledger and its coverage report from source.

WHAT THIS IS
------------
Two committed artifacts come out of this one script, because they are two
readings of the same derivation and deriving them separately would let them
disagree:

``pcb/library/part_orientation.json``
    The ledger. Its MEASURED rows are derived, never authored: each one is
    ``pcb_worker.part_orientation`` run over one of our seed footprints and the
    vendor's package drawing of the part we buy against it. Its DECLARED rows
    are read from the authored source below.

``pcb/library/part_orientation_coverage.md``
    Which shipped footprints that ledger accounts for, and — the part worth
    committing — which ones it does not. The coverage gap is a pure function of
    the acquisition lock and the ledger, so it belongs in the tree where a
    person reads it, not in a command they have to know to run.

Modelled on ``gen_notice.py``, deliberately: one ``generate()`` per artifact
that both the CLI and the test call, a ``--check`` mode that writes nothing and
exits 1 on drift, and committed output whose byte-identity is pinned by a test.
The library's generated artifacts should be regenerated and gated alike.

THE TWO SOURCES, AND WHY DECLARATIONS ARE NOT READ BACK OUT OF THE OUTPUT
-------------------------------------------------------------------------
MEASURED rows come from ``pcb/worker/tests/testdata/vendor_footprints/`` — the
committed LCSC/EasyEDA package payloads plus the ``index.json`` that pairs each
part with the seed footprint it is bought for.

DECLARED rows — the human-authored "there is nothing to measure here"
statements for mounting holes, test points, fiducials, coupon fixtures,
synthesized fixture lands and synthetic composites — come from
``pcb/library/part_orientation_declared.json``, an AUTHORED file that is not
generated by anything.

They used to be read back out of the previous ledger and passed through. That
made them un-gated: a declaration deleted from the output regenerated cleanly,
because the only record of it was the output. An authored source makes a
declaration a thing you edit and the artifact a thing you derive, which is what
``--check`` is able to say something about.

CONVERGENCE
-----------
Both artifacts are rendered WHOLESALE on every run, so:

* re-running with nothing changed produces byte-identical output;
* re-running after a seed footprint is edited changes exactly that footprint's
  rows, and nothing else drifts along with it;
* a pair removed from the corpus, or a declaration removed from the source,
  leaves no orphan row behind.

NO CLOCK, NO VERSION STAMP
--------------------------
Nothing here writes a timestamp or a tool version into either output. Either
would make every regeneration a diff and destroy the one property these files
are for. When a row was measured is a question ``git log`` answers better.

WHERE THE VENDOR SIDE LIVES, AND WHY IT IS NOT IN THE LIBRARY
--------------------------------------------------------------
The payloads live under the test corpus rather than under ``pcb/library/`` ON
PURPOSE: they are third-party vendor content, and ``pcb/library/`` is the
shipped tree whose third-party obligations ``gen_notice.py`` certifies from the
acquisition lock. Moving them there would put unattributed third-party data on
the release path that the NOTICE gate does not walk. The consequence — that a
shipped install cannot re-measure — is why every measured row pins
``footprint_sha256``: our own edits stay detectable without the payloads.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys

from pathlib import Path
from typing import Union

# pcb/scripts/this.py -> pcb/, so the worker package is a sibling directory.
# Same convention as gen_notice.py.
PCB = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PCB / "worker"))

from pcb_worker import orientation_coverage as oc  # noqa: E402
from pcb_worker import orientation_ledger as ol  # noqa: E402
from pcb_worker import part_orientation as po  # noqa: E402
from pcb_worker.footprints import (  # noqa: E402
    DEFAULT_LOCKFILE,
    load_lockfile,
    resolve_footprint,
)

DEFAULT_PAYLOAD_DIR = PCB / "worker" / "tests" / "testdata" / "vendor_footprints"
DEFAULT_LEDGER_PATH = ol.DEFAULT_LEDGER_PATH
#: The authored declarations. Beside the ledger it feeds, because a reader who
#: opens one wants the other.
DEFAULT_DECLARED_PATH = PCB / "library" / "part_orientation_declared.json"
DEFAULT_COVERAGE_PATH = PCB / "library" / "part_orientation_coverage.md"
REGEN_COMMAND = "python3 pcb/scripts/gen_part_orientation.py"

DECLARED_SCHEMA_VERSION = 1
#: The only keys an authored declaration may state. A declaration says there is
#: nothing to measure, so every field beyond the identity and the reason would
#: be a number it must not carry — and the ledger's own validation refuses one
#: anyway. Refusing here as well means the error names the file a human edits.
_DECLARED_SOURCE_KEYS = ("footprint", "reason")


class GenerationError(RuntimeError):
    """An artifact could not be derived. Never partially written."""


def _index(payload_dir: Path) -> dict:
    """The (part -> {footprint, house}) pairing, read from the corpus."""
    path = payload_dir / "index.json"
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise GenerationError(f"cannot read the pairing index {path}: {exc}") from exc
    if not isinstance(raw, dict) or not raw:
        raise GenerationError(f"{path} must be a non-empty object of part -> pairing")
    for part, entry in sorted(raw.items()):
        for field in ("footprint", "house"):
            value = entry.get(field) if isinstance(entry, dict) else None
            if not isinstance(value, str) or not value.strip():
                raise GenerationError(
                    f"{path}: {part} is missing a non-empty {field!r}. A pairing "
                    f"that does not name both the footprint and the house it is "
                    f"bought from names no orderable part")
    return raw


def _declared(declared_path: Path, lock: dict) -> tuple:
    """The authored declarations, as validated footprint-wide ledger rows.

    Three things are checked HERE, in terms of the file a human edits, rather
    than left to the ledger's own validation which speaks about the artifact:

    * a declaration names a footprint the acquisition lock carries — a
      statement about a drawing we no longer ship is stale, not harmless;
    * no footprint is declared twice;
    * a declaration carries a reason and nothing else. The reason is the whole
      content of the row: "no vendor drawing exists" is a claim about the world
      and an unexplained claim is indistinguishable from a shrug.
    """
    try:
        raw = json.loads(declared_path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise GenerationError(
            f"cannot read the declarations at {declared_path}: {exc}. A missing "
            f"declarations file is not an empty one — every footprint that has "
            f"nothing orderable behind it would silently become unknown") from exc
    except ValueError as exc:
        raise GenerationError(f"{declared_path} is not valid JSON: {exc}") from exc

    if not isinstance(raw, dict):
        raise GenerationError(f"{declared_path} must be a JSON object")
    version = raw.get("schema_version")
    if version != DECLARED_SCHEMA_VERSION:
        raise GenerationError(
            f"{declared_path}: schema_version {version!r} is not "
            f"{DECLARED_SCHEMA_VERSION}")
    rows_raw = raw.get("declared")
    if not isinstance(rows_raw, list):
        raise GenerationError(
            f"{declared_path}: `declared` must be a list; got "
            f"{type(rows_raw).__name__}. It is written even when empty, so an "
            f"absent one means a truncated file")
    unknown_top = sorted(set(raw) - {"schema_version", "declared"})
    if unknown_top:
        raise GenerationError(
            f"{declared_path}: unknown top-level key(s) {'/'.join(unknown_top)}")

    rows = []
    seen = set()
    for item in rows_raw:
        if not isinstance(item, dict):
            raise GenerationError(
                f"{declared_path}: a declaration must be an object; got "
                f"{type(item).__name__}")
        extra = sorted(set(item) - set(_DECLARED_SOURCE_KEYS))
        if extra:
            raise GenerationError(
                f"{declared_path}: declaration {item.get('footprint')!r} states "
                f"{'/'.join(extra)}, which a declaration may not carry. A row "
                f"that says there is nothing to measure must carry no "
                f"measurement; it takes {'/'.join(_DECLARED_SOURCE_KEYS)}")
        ref = item.get("footprint")
        reason = item.get("reason")
        if not isinstance(ref, str) or not ref.strip():
            raise GenerationError(
                f"{declared_path}: a declaration needs a non-empty footprint")
        if not isinstance(reason, str) or not reason.strip():
            raise GenerationError(
                f"{declared_path}: {ref} must carry a reason. 'No vendor "
                f"drawing' is a claim about the world, and an unexplained claim "
                f"is indistinguishable from a shrug")
        if ref in seen:
            raise GenerationError(
                f"{declared_path}: {ref} is declared twice. One footprint, one "
                f"statement — a duplicate makes which reason wins a question "
                f"about file order")
        if ref not in lock:
            raise GenerationError(
                f"{declared_path}: {ref} is not in the acquisition lock. A "
                f"declaration is a statement about a drawing we SHIP; one about "
                f"a drawing we do not is stale and would never be read")
        seen.add(ref)
        rows.append(ol.OrientationRecord(
            footprint=ref, house=None, part=None,
            verdict=po.VERDICT_NO_REFERENCE, declared=True, reason=reason))
    return tuple(rows)


def _measured(payload_dir: Path, lock: dict, lockfile) -> tuple:
    """Every pair in the corpus, measured from the drawings themselves."""
    rows = []
    for part, pairing in sorted(_index(payload_dir).items()):
        ref = pairing["footprint"]
        entry = lock.get(ref)
        if entry is None:
            raise GenerationError(
                f"{part}: the corpus pairs it with {ref!r}, which the "
                f"acquisition lock does not carry — the pairing names a "
                f"footprint we do not ship")
        payload_path = payload_dir / f"{part}.json"
        try:
            payload_bytes = payload_path.read_bytes()
        except OSError as exc:
            raise GenerationError(
                f"{part}: cannot read its vendor payload {payload_path}: {exc}"
            ) from exc
        try:
            payload = json.loads(payload_bytes.decode("utf-8"))
        except (UnicodeDecodeError, ValueError) as exc:
            raise GenerationError(f"{payload_path} is not valid JSON: {exc}") from exc

        # resolve_footprint re-verifies the on-disk bytes against the lock pin,
        # so the sha recorded beside the measurement is the sha of the drawing
        # that was actually measured, not a claim copied out of the lock.
        parsed = resolve_footprint(ref, lockfile=lockfile)
        measurement = po.measure_footprint_against_part(parsed, payload, lcsc=part)
        rows.append(ol.record_from_measurement(
            ref, pairing["house"], part, measurement,
            footprint_sha256=str(entry["sha256"]),
            vendor_sha256=hashlib.sha256(payload_bytes).hexdigest(),
        ))
    return tuple(rows)


def build(payload_dir: Union[str, Path, None] = None,
          lockfile: Union[str, Path, None] = None,
          declared_path: Union[str, Path, None] = None) -> tuple:
    """``(ledger, lock)`` — the one derivation both artifacts are rendered from.

    A footprint that is both declared and measured is refused here. It is a
    contradiction, not a merge: the declaration says nothing orderable is drawn
    like this, and the measurement is a vendor's drawing of an orderable part
    that is. Letting both stand would leave which one a consumer sees to
    ``lookup``'s precedence rule, which exists for a different purpose.
    """
    payload_dir = Path(payload_dir) if payload_dir else DEFAULT_PAYLOAD_DIR
    declared_path = (Path(declared_path) if declared_path
                     else DEFAULT_DECLARED_PATH)
    lockfile = Path(lockfile) if lockfile is not None else DEFAULT_LOCKFILE
    lock = load_lockfile(lockfile)

    declared = _declared(declared_path, lock)
    measured = _measured(payload_dir, lock, lockfile)

    clash = sorted({r.footprint for r in declared} & {r.footprint for r in measured})
    if clash:
        raise GenerationError(
            f"{'/'.join(clash)}: declared to have no vendor drawing, and also "
            f"measured against one. Delete the declaration in {declared_path} "
            f"or the pairing in the corpus — a footprint cannot be both")

    return ol.OrientationLedger(declared=declared, measured=measured), lock


def generate(payload_dir: Union[str, Path, None] = None,
             lockfile: Union[str, Path, None] = None,
             declared_path: Union[str, Path, None] = None) -> str:
    """The LEDGER's canonical bytes. The one function both ``main`` and the
    test call, so the CLI and the suite can never derive the file two different
    ways."""
    ledger, _ = build(payload_dir, lockfile, declared_path)
    return ledger.to_text()


def generate_coverage(payload_dir: Union[str, Path, None] = None,
                      lockfile: Union[str, Path, None] = None,
                      declared_path: Union[str, Path, None] = None) -> str:
    """The COVERAGE REPORT's canonical bytes, folded from the same derivation."""
    ledger, lock = build(payload_dir, lockfile, declared_path)
    return oc.coverage(ledger, lock).to_markdown()


def main(argv: Union[list, None] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true",
        help="Write nothing; exit 1 if either committed artifact would differ "
             "from what this run derives.")
    ap.add_argument(
        "--coverage", action="store_true",
        help="Write nothing; print the coverage report to stdout. What is "
             "measured, what is declared, and what an order could still stop "
             "on.")
    ap.add_argument("--payloads", default=None,
                    help="Override the vendor payload + pairing directory.")
    ap.add_argument("--declared", default=None,
                    help="Override the authored declarations file.")
    ap.add_argument("--out", default=None,
                    help="Override the ledger path (default: "
                         "pcb/library/part_orientation.json, resolved relative "
                         "to this script, not the caller's cwd). The coverage "
                         "report is written beside it.")
    args = ap.parse_args(argv)

    out_path = Path(args.out) if args.out else DEFAULT_LEDGER_PATH
    coverage_path = (out_path.with_name(DEFAULT_COVERAGE_PATH.name)
                     if args.out else DEFAULT_COVERAGE_PATH)
    try:
        ledger, lock = build(args.payloads, None, args.declared)
        body = ledger.to_text()
        report = oc.coverage(ledger, lock)
        coverage_body = report.to_markdown()
    except Exception as exc:
        print(f"gen_part_orientation: cannot derive the ledger: {exc}",
              file=sys.stderr)
        return 1

    if args.coverage:
        sys.stdout.write(coverage_body)
        return 0

    if args.check:
        drifted = []
        for path, want in ((out_path, body), (coverage_path, coverage_body)):
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != want:
                drifted.append(path)
        if not drifted:
            return 0
        print(f"gen_part_orientation: {', '.join(str(p) for p in drifted)} "
              f"has DRIFTED from the sources it is derived from. Regenerate "
              f"with `{REGEN_COMMAND}` and READ the diff: a changed offset "
              f"means either the supplier redrew the package or our footprint "
              f"moved, and both need a human to look at the board before the "
              f"next order goes out; a changed coverage report means the set of "
              f"drawings an order can stop on is not what was last agreed.",
              file=sys.stderr)
        return 1

    for path, want in ((out_path, body), (coverage_path, coverage_body)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(want, encoding="utf-8")
        print(f"gen_part_orientation: wrote {path}")

    counts = report.counts()
    print(f"gen_part_orientation: {counts[oc.STATE_MEASURED]} measured, "
          f"{counts[oc.STATE_NO_REFERENCE]} declared, "
          f"{counts[oc.STATE_UNKNOWN]} UNKNOWN of "
          f"{counts['total']} shipped footprints")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
